[package]
name = "bevy_game"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16"
bevy_common_assets = { version = "0.13.0", features = ["ron"] }
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
